# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TELA_LAYOUT.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from imagens_rc import *

class Tela_layout(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 801, 291))
        self.stackedWidget.setObjectName("stackedWidget")
        self.imagem = QtWidgets.QWidget()
        self.imagem.setObjectName("imagem")
        self.label = QtWidgets.QLabel(self.imagem)
        self.label.setGeometry(QtCore.QRect(110, 0, 581, 271))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.imagem)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(370, 460, 93, 28))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/imagens/layout.png\"/></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "ok"))
#import imagens_rc
